-- =============================================================================
-- classeur_2026-09-25.sql — page « Classeur » : schéma complet (portage de
-- l'application de bureau Registre, github.com/Owltus/Registre).
--
-- Application : `supabase db query --linked -f supabase/classeur_2026-09-25.sql`
-- AUTORITÉ UNIQUE pour toutes les tables `classeur_*` : rejouable (idempotent),
-- à faire évoluer ICI (jamais de DDL à la volée).
--
-- Contexte : Registre stockait ces données dans un SQLite local (7 tables +
--   historique de fusion). Le Back Office les porte dans Postgres avec les
--   pratiques du projet : RLS par page à trois niveaux, estampillage d'auteur
--   par trigger via private.keep_author, aucun privilège pour anon, aucune
--   fonction security definer dans public.
--
-- Modèle :
--   classeur_classeurs        conteneur (nom, icône Lucide, établissement)
--   classeur_chapters         chapitre d'un classeur
--   classeur_periodicites     référentiel des périodicités de suivi (seed)
--   classeur_documents        document Markdown d'un chapitre
--   classeur_tracking_sheets  feuille de suivi périodique
--   classeur_signature_sheets feuille d'émargement (N lignes)
--   classeur_intercalaires    page de séparation
--   classeur_merge_history    instantanés JSON pris avant chaque fusion
--
-- Droits (plan/page-classeur/00-INDEX.md) :
--   lecture  (rang 1) : tout lire, imprimer.
--   ecriture (rang 2) : créer, modifier, réordonner, supprimer (douce),
--                       importer, fusionner (insert dans l'historique).
--   gestion           : suppression PHYSIQUE d'un classeur ou d'une entrée
--                       d'historique (tout le reste est une suppression douce
--                       = update de deleted_at).
--   Aucune fenêtre de grâce : un classeur réglementaire n'a pas de « jour ».
--
-- Innocuité : create table if not exists, create or replace, drop policy if
--   exists puis create. Ne touche à aucune table existante. Aucune donnée
--   réécrite. Le seed des périodicités est protégé par `on conflict do nothing`
--   sur le libellé.
--
-- Vérification : section finale (lecture seule), tout doit être `true`.
-- =============================================================================

begin;

-- =============================================================================
-- 1) TABLES
-- =============================================================================

create table if not exists public.classeur_classeurs (
  id                        bigint generated by default as identity primary key,
  uuid                      uuid        not null default gen_random_uuid() unique,
  name                      text        not null default 'Mon classeur',
  icon                      text        not null default 'BookOpen',
  etablissement             text        not null default '',
  etablissement_complement  text        not null default '',
  sort_order                integer     not null default 0,
  deleted_at                timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  created_by                uuid        references public.profiles(id) on delete set null
);

create table if not exists public.classeur_chapters (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  label        text        not null,
  icon         text        not null default 'FileText',
  description  text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_chapters_classeur_idx
  on public.classeur_chapters (classeur_id) where deleted_at is null;

create table if not exists public.classeur_periodicites (
  id          bigint  generated by default as identity primary key,
  label       text    not null unique,
  nombre      integer not null default 8,
  sort_order  integer not null default 0
);

create table if not exists public.classeur_documents (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  content      text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_documents_chapter_idx
  on public.classeur_documents (chapter_id) where deleted_at is null;

create table if not exists public.classeur_tracking_sheets (
  id              bigint generated by default as identity primary key,
  uuid            uuid        not null default gen_random_uuid() unique,
  chapter_id      bigint      not null references public.classeur_chapters(id) on delete cascade,
  title           text        not null,
  periodicite_id  bigint      not null references public.classeur_periodicites(id),
  sort_order      integer     not null default 0,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  created_by      uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_tracking_sheets_chapter_idx
  on public.classeur_tracking_sheets (chapter_id) where deleted_at is null;

create table if not exists public.classeur_signature_sheets (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  nombre       integer     not null default 14 check (nombre between 1 and 60),
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_signature_sheets_chapter_idx
  on public.classeur_signature_sheets (chapter_id) where deleted_at is null;

create table if not exists public.classeur_intercalaires (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_intercalaires_chapter_idx
  on public.classeur_intercalaires (chapter_id) where deleted_at is null;

-- 2026-09-26 (classeur_images_table_2026-09-26.sql) : MÉDIATHÈQUE — une
-- image appartient au classeur, les documents la référencent par `chemin`
-- dans leur Markdown ; l'usage est calculé par l'app, jamais stocké.
create table if not exists public.classeur_images (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  chemin       text        not null unique
                           check (chemin ~ '^[0-9]{1,12}/[0-9a-f-]{36}\.webp$'),
  nom          text        not null default '',
  taille       integer     not null default 0 check (taille >= 0),
  largeur      integer     not null default 0 check (largeur >= 0),
  hauteur      integer     not null default 0 check (hauteur >= 0),
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_images_classeur_idx
  on public.classeur_images (classeur_id, created_at desc) where deleted_at is null;

-- 2026-09-26 (classeur_images_table_2026-09-26.sql) : MÉDIATHÈQUE — une
-- image appartient au classeur, les documents la référencent par `chemin`
-- dans leur Markdown ; l'usage est calculé par l'app, jamais stocké.
create table if not exists public.classeur_images (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  chemin       text        not null unique
                           check (chemin ~ '^[0-9]{1,12}/[0-9a-f-]{36}\.webp$'),
  nom          text        not null default '',
  taille       integer     not null default 0 check (taille >= 0),
  largeur      integer     not null default 0 check (largeur >= 0),
  hauteur      integer     not null default 0 check (hauteur >= 0),
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_images_classeur_idx
  on public.classeur_images (classeur_id, created_at desc) where deleted_at is null;

create table if not exists public.classeur_merge_history (
  id           bigint generated by default as identity primary key,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  merged_at    timestamptz not null default now(),
  source_name  text        not null default '',
  inserted     integer     not null default 0,
  updated      integer     not null default 0,
  unchanged    integer     not null default 0,
  skipped      integer     not null default 0,
  snapshot     jsonb       not null,
  -- 2026-09-26 (classeur_points_restauration_2026-09-26.sql) : points de
  -- restauration mineurs/majeurs. kind : auto | manuel | fusion | securite.
  kind         text        not null default 'fusion'
                           check (kind in ('auto', 'manuel', 'fusion', 'securite')),
  label        text        not null default '',
  taille       integer,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
alter table public.classeur_merge_history
  add column if not exists kind text not null default 'fusion'
    check (kind in ('auto', 'manuel', 'fusion', 'securite')),
  add column if not exists label text not null default '',
  add column if not exists taille integer;
create index if not exists classeur_merge_history_classeur_idx
  on public.classeur_merge_history (classeur_id, merged_at desc);
create index if not exists classeur_merge_history_kind_idx
  on public.classeur_merge_history (classeur_id, kind, merged_at desc);

-- Poids de l'instantané, posé à l'insertion (affiché dans le dialogue).
create or replace function public.classeur_merge_history_taille()
returns trigger
language plpgsql
security invoker
set search_path to 'public'
as $function$
begin
  new.taille := pg_column_size(new.snapshot);
  return new;
end;
$function$;
revoke execute on function public.classeur_merge_history_taille() from public, anon, authenticated;
drop trigger if exists classeur_merge_history_taille on public.classeur_merge_history;
create trigger classeur_merge_history_taille
  before insert on public.classeur_merge_history
  for each row execute function public.classeur_merge_history_taille();

-- =============================================================================
-- 2) SEED — périodicités (identique à Registre ; `nombre` = colonnes du tableau)
-- =============================================================================
insert into public.classeur_periodicites (label, nombre, sort_order) values
  ('Mensuel',        8, 1),
  ('Sesquimestriel', 8, 2),
  ('Semestriel',     8, 3),
  ('Annuel',         8, 4),
  ('Biennale',       8, 5),
  ('Triennal',       4, 6),
  ('Quadriennal',    4, 7),
  ('Quinquennal',    4, 8),
  ('Non défini',     8, 9)
on conflict (label) do nothing;

-- =============================================================================
-- 3) ESTAMPILLAGE — une fonction trigger pour les 7 tables (invoker, fermée)
-- =============================================================================
create or replace function public.classeur_stamp()
returns trigger
language plpgsql
security invoker
set search_path to 'public'
as $function$
begin
  -- 2026-09-25 (classeur_stamp_updated_at_2026-09-25.sql) : un `updated_at`
  -- FOURNI par le client est respecté (fusion JSON : horodatage du fichier,
  -- règle « dernier écrit gagne ») ; sinon now(), comme avant.
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    if new.updated_at is null then
      new.updated_at := now();
    end if;
  else
    new.created_by := private.keep_author(new.created_by, old.created_by);
    if new.updated_at is not distinct from old.updated_at then
      new.updated_at := now();
    end if;
  end if;
  return new;
end;
$function$;
revoke execute on function public.classeur_stamp() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_documents',
    'classeur_tracking_sheets', 'classeur_signature_sheets',
    'classeur_intercalaires', 'classeur_merge_history', 'classeur_images'
  ] loop
    execute format('drop trigger if exists classeur_stamp on public.%I', t);
    execute format(
      'create trigger classeur_stamp before insert or update on public.%I
         for each row execute function public.classeur_stamp()', t);
  end loop;
end $$;

-- =============================================================================
-- 4) PRIVILÈGES — anon : rien ; authenticated : DML sous RLS
-- =============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history', 'classeur_images'
  ] loop
    execute format('revoke all on table public.%I from public, anon', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on sequence public.%I_id_seq from public, anon', t);
    execute format('grant usage, select on sequence public.%I_id_seq to authenticated', t);
  end loop;
end $$;

-- =============================================================================
-- 5) RLS — modèle literie.sql, appels enveloppés en (select …)
-- =============================================================================

-- Lecture : rang >= 1 sur les 9 tables.
do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history', 'classeur_images'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.page_level_rank(private.get_page_level(''classeur''))) >= 1)', t, t);
  end loop;
end $$;

-- Écriture PAR PROPRIÉTAIRE (2026-09-26, classeur_proprietaire_2026-09-26.sql,
-- modèle Affichage) : `ecriture` ne modifie que ses classeurs, `gestion` tout.
-- Bloc IDENTIQUE à celui du script daté ; le faire évoluer aux deux endroits.

-- 1) Aides ------------------------------------------------------------------

create or replace function private.classeur_write_ok(p_classeur_id bigint)
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select
    (select private.get_page_level('classeur')) = 'gestion'
    or (
      (select private.page_level_rank(private.get_page_level('classeur'))) >= 2
      and exists (
        select 1 from public.classeur_classeurs c
        where c.id = p_classeur_id and c.created_by = auth.uid()
      )
    );
$function$;

create or replace function private.classeur_chapter_write_ok(p_chapter_id bigint)
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select coalesce(
    (select private.classeur_write_ok(ch.classeur_id)
       from public.classeur_chapters ch
      where ch.id = p_chapter_id),
    false);
$function$;

revoke execute on function private.classeur_write_ok(bigint) from public, anon;
grant execute on function private.classeur_write_ok(bigint) to authenticated, service_role;
revoke execute on function private.classeur_chapter_write_ok(bigint) from public, anon;
grant execute on function private.classeur_chapter_write_ok(bigint) to authenticated, service_role;

-- 2) Classeur : insert rang >= 2, update gestion ou propriétaire -------------

drop policy if exists "classeur_classeurs insert (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs insert (page:classeur)"
  on public.classeur_classeurs for insert to authenticated
  with check ((select private.page_level_rank(private.get_page_level('classeur'))) >= 2);

drop policy if exists "classeur_classeurs update (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs update (page:classeur)"
  on public.classeur_classeurs for update to authenticated
  using ((select private.classeur_write_ok(id)))
  with check ((select private.classeur_write_ok(id)));

-- 3) Chapitres : par le classeur parent ---------------------------------------

drop policy if exists "classeur_chapters insert (page:classeur)" on public.classeur_chapters;
create policy "classeur_chapters insert (page:classeur)"
  on public.classeur_chapters for insert to authenticated
  with check ((select private.classeur_write_ok(classeur_id)));

drop policy if exists "classeur_chapters update (page:classeur)" on public.classeur_chapters;
create policy "classeur_chapters update (page:classeur)"
  on public.classeur_chapters for update to authenticated
  using ((select private.classeur_write_ok(classeur_id)))
  with check ((select private.classeur_write_ok(classeur_id)));

-- 4) Éléments : par le chapitre parent ----------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires'
  ] loop
    execute format('drop policy if exists "%s insert (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s insert (page:classeur)" on public.%I for insert to authenticated
         with check ((select private.classeur_chapter_write_ok(chapter_id)))', t, t);
    execute format('drop policy if exists "%s update (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s update (page:classeur)" on public.%I for update to authenticated
         using ((select private.classeur_chapter_write_ok(chapter_id)))
         with check ((select private.classeur_chapter_write_ok(chapter_id)))', t, t);
  end loop;
end $$;

-- 5) Points de restauration : par le classeur ---------------------------------

drop policy if exists "classeur_merge_history insert (page:classeur)" on public.classeur_merge_history;
create policy "classeur_merge_history insert (page:classeur)"
  on public.classeur_merge_history for insert to authenticated
  with check ((select private.classeur_write_ok(classeur_id)));

drop policy if exists "classeur_merge_history delete (page:classeur)" on public.classeur_merge_history;
create policy "classeur_merge_history delete (page:classeur)"
  on public.classeur_merge_history for delete to authenticated
  using (
    (select private.get_page_level('classeur')) = 'gestion'
    or (kind = 'auto' and (select private.classeur_write_ok(classeur_id)))
  );

-- 6) Médiathèque : insert/update par le classeur, pas de delete (douce) ---

drop policy if exists "classeur_images insert (page:classeur)" on public.classeur_images;
create policy "classeur_images insert (page:classeur)"
  on public.classeur_images for insert to authenticated
  with check ((select private.classeur_write_ok(classeur_id)));

drop policy if exists "classeur_images update (page:classeur)" on public.classeur_images;
create policy "classeur_images update (page:classeur)"
  on public.classeur_images for update to authenticated
  using ((select private.classeur_write_ok(classeur_id)))
  with check ((select private.classeur_write_ok(classeur_id)));

-- Suppression PHYSIQUE d'un classeur : gestion seule (les enfants suivent par
-- cascade). Les chapitres et éléments n'ont PAS de policy delete : leur
-- suppression est douce.
drop policy if exists "classeur_classeurs delete (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs delete (page:classeur)"
  on public.classeur_classeurs for delete to authenticated
  using ((select private.get_page_level('classeur')) = 'gestion');


-- 7) HISTORIQUE DES DOCUMENTS (2026-09-27) — bloc IDENTIQUE à
-- classeur_versions_documents_2026-09-27.sql (versions écrites par trigger,
-- lecture rang >= 1, aucune écriture pour authenticated).

create table if not exists public.classeur_document_versions (
  id           bigint generated by default as identity primary key,
  document_id  bigint      not null references public.classeur_documents(id) on delete cascade,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  title        text        not null default '',
  description  text        not null default '',
  content      text        not null default '',
  origine      text        not null default 'enregistrement'
                           check (origine in ('creation', 'enregistrement', 'etat_initial')),
  auteur       text        not null default '',
  created_by   uuid        references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists classeur_document_versions_doc_idx
  on public.classeur_document_versions (document_id, created_at desc, id desc);

create or replace function private.classeur_document_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_classeur bigint;
  v_uid      uuid := auth.uid();
  v_auteur   text := '';
begin
  if tg_op = 'UPDATE'
     and new.title is not distinct from old.title
     and new.description is not distinct from old.description
     and new.content is not distinct from old.content then
    return null;
  end if;

  select ch.classeur_id into v_classeur
    from public.classeur_chapters ch where ch.id = new.chapter_id;
  if v_classeur is null then
    return null;
  end if;

  if v_uid is not null then
    select coalesce(
             nullif(btrim(coalesce(p.first_name, '') || ' ' || coalesce(p.last_name, '')), ''),
             nullif(btrim(p.display_name), ''),
             '')
      into v_auteur
      from public.profiles p where p.id = v_uid;
  end if;

  -- État d'avant le suivi : conservé une fois, au premier enregistrement.
  if tg_op = 'UPDATE' and not exists (
       select 1 from public.classeur_document_versions v where v.document_id = new.id) then
    insert into public.classeur_document_versions
      (document_id, classeur_id, title, description, content, origine, auteur, created_by, created_at)
    values
      (old.id, v_classeur, old.title, old.description, old.content, 'etat_initial', '', null, old.updated_at);
  end if;

  insert into public.classeur_document_versions
    (document_id, classeur_id, title, description, content, origine, auteur, created_by)
  values
    (new.id, v_classeur, new.title, new.description, new.content,
     case tg_op when 'INSERT' then 'creation' else 'enregistrement' end,
     coalesce(v_auteur, ''), v_uid);

  -- Borne : 50 versions par document, les plus récentes.
  delete from public.classeur_document_versions v
   where v.document_id = new.id
     and v.id not in (
       select w.id from public.classeur_document_versions w
        where w.document_id = new.id
        order by w.created_at desc, w.id desc
        limit 50);

  return null;
end;
$$;
revoke execute on function private.classeur_document_version() from public, anon, authenticated;

drop trigger if exists classeur_document_version on public.classeur_documents;
create trigger classeur_document_version
  after insert or update of title, description, content on public.classeur_documents
  for each row execute function private.classeur_document_version();

-- Privilèges : anon rien ; authenticated LECTURE seule, sous RLS.
revoke all on table public.classeur_document_versions from public, anon, authenticated;
grant select on table public.classeur_document_versions to authenticated;
alter table public.classeur_document_versions enable row level security;
revoke all on sequence public.classeur_document_versions_id_seq from public, anon, authenticated;

drop policy if exists "classeur_document_versions read (page:classeur)" on public.classeur_document_versions;
create policy "classeur_document_versions read (page:classeur)"
  on public.classeur_document_versions for select to authenticated
  -- Remplacée par le niveau effectif en section 8 (définie après).
  using ((select private.page_level_rank(private.get_page_level('classeur'))) >= 1);



-- 8) ACCÈS PAR CLASSEUR (2026-09-28) — bloc IDENTIQUE à
-- classeur_acces_2026-09-28.sql. Placé EN DERNIER : ses policies de
-- lecture remplacent celles « rang >= 1 » des sections 5 et 7.

-- 1) Accès pour tous ----------------------------------------------------------
alter table public.classeur_classeurs
  add column if not exists acces_tous text not null default 'lecture';
do $$ begin
  if not exists (select 1 from pg_constraint
                  where conname = 'classeur_classeurs_acces_tous_check') then
    alter table public.classeur_classeurs
      add constraint classeur_classeurs_acces_tous_check
      check (acces_tous in ('aucun', 'lecture', 'ecriture'));
  end if;
end $$;

-- 2) Exceptions par personne ----------------------------------------------------
create table if not exists public.classeur_acces (
  id           bigint generated by default as identity primary key,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  user_id      uuid        not null references public.profiles(id) on delete cascade,
  niveau       text        not null check (niveau in ('aucun', 'lecture', 'ecriture')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null,
  unique (classeur_id, user_id)
);
create index if not exists classeur_acces_user_idx on public.classeur_acces (user_id);

drop trigger if exists classeur_stamp on public.classeur_acces;
create trigger classeur_stamp before insert or update on public.classeur_acces
  for each row execute function public.classeur_stamp();

revoke all on table public.classeur_acces from public, anon;
grant select, insert, update, delete on table public.classeur_acces to authenticated;
alter table public.classeur_acces enable row level security;
revoke all on sequence public.classeur_acces_id_seq from public, anon;
grant usage, select on sequence public.classeur_acces_id_seq to authenticated;

-- 3) Le niveau effectif : UNE fonction, source de vérité ------------------------
-- Calcul À PARTIR DES VALEURS DE LA LIGNE : la policy de lecture de
-- `classeur_classeurs` l'appelle avec les colonnes de la ligne elle-même.
-- Une création relit la ligne insérée (`insert … returning`), invisible à
-- une recherche par identifiant pendant l'insertion : chercher la ligne par
-- `id` refusait toute création (trouvé à la répétition du 2026-09-28).
create or replace function private.classeur_niveau_de(
  p_classeur_id bigint, p_created_by uuid, p_acces_tous text)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_page   text := private.get_page_level('classeur');
  v_uid    uuid := auth.uid();
  v_droit  text;
begin
  if v_page is null then
    return 'aucun';
  end if;
  if v_page = 'gestion' then
    return 'gestion';
  end if;
  v_droit := coalesce(
    (select a.niveau from public.classeur_acces a
      where a.classeur_id = p_classeur_id and a.user_id = v_uid),
    case when p_created_by = v_uid then 'ecriture' end,
    p_acces_tous);
  if v_droit is null or v_droit = 'aucun' then
    return 'aucun';
  end if;
  -- Plafond : le droit de page borne le droit sur le classeur.
  if v_page = 'lecture' then
    return 'lecture';
  end if;
  if v_page = 'ecriture' then
    return v_droit;
  end if;
  return 'aucun';
end;
$$;

-- Par identifiant : pour les tables enfants (chapitres, éléments, images…).
create or replace function private.classeur_niveau(p_classeur_id bigint)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when private.get_page_level('classeur') is not distinct from 'gestion' then 'gestion'
    else coalesce(
      (select private.classeur_niveau_de(c.id, c.created_by, c.acces_tous)
         from public.classeur_classeurs c where c.id = p_classeur_id),
      'aucun')
  end;
$$;

create or replace function private.classeur_lecture_ligne(
  p_classeur_id bigint, p_created_by uuid, p_acces_tous text)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau_de(p_classeur_id, p_created_by, p_acces_tous)
               in ('lecture', 'ecriture', 'gestion'); $$;

create or replace function private.classeur_lecture_ok(p_classeur_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau(p_classeur_id) in ('lecture', 'ecriture', 'gestion'); $$;

-- Même nom, même signature qu'avant : les policies d'écriture existantes
-- (chapitres, éléments, médiathèque, points, stockage) suivent seules.
create or replace function private.classeur_write_ok(p_classeur_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau(p_classeur_id) in ('ecriture', 'gestion'); $$;

create or replace function private.classeur_chapter_read_ok(p_chapter_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$
  select coalesce(
    (select private.classeur_lecture_ok(ch.classeur_id)
       from public.classeur_chapters ch where ch.id = p_chapter_id),
    false);
$$;

create or replace function private.classeur_gestion_ok()
returns boolean language sql stable security definer set search_path = ''
as $$ select private.get_page_level('classeur') is not distinct from 'gestion'; $$;

do $$
declare f text;
begin
  foreach f in array array[
    'private.classeur_niveau_de(bigint, uuid, text)', 'private.classeur_niveau(bigint)',
    'private.classeur_lecture_ligne(bigint, uuid, text)', 'private.classeur_lecture_ok(bigint)',
    'private.classeur_write_ok(bigint)', 'private.classeur_chapter_read_ok(bigint)',
    'private.classeur_chapter_write_ok(bigint)', 'private.classeur_gestion_ok()'
  ] loop
    execute format('revoke execute on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated, service_role', f);
  end loop;
end $$;

-- 4) Lecture : le niveau effectif partout ---------------------------------------
drop policy if exists "classeur_classeurs read (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs read (page:classeur)"
  on public.classeur_classeurs for select to authenticated
  using (private.classeur_lecture_ligne(id, created_by, acces_tous));

do $$
declare t text;
begin
  foreach t in array array[
    'classeur_chapters', 'classeur_merge_history', 'classeur_images',
    'classeur_document_versions'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.classeur_lecture_ok(classeur_id)))', t, t);
  end loop;
  foreach t in array array[
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.classeur_chapter_read_ok(chapter_id)))', t, t);
  end loop;
end $$;

drop policy if exists "classeur-images read (page:classeur)" on storage.objects;
create policy "classeur-images read (page:classeur)"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'classeur-images'
    and array_length(storage.foldername(name), 1) = 1
    and (storage.foldername(name))[1] ~ '^[0-9]{1,12}$'
    and (select private.classeur_lecture_ok(((storage.foldername(name))[1])::bigint))
  );

-- 5) Exceptions : chacun lit les siennes, la gestion gère tout ----------------
drop policy if exists "classeur_acces read" on public.classeur_acces;
create policy "classeur_acces read"
  on public.classeur_acces for select to authenticated
  using (user_id = (select auth.uid()) or (select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces insert (gestion)" on public.classeur_acces;
create policy "classeur_acces insert (gestion)"
  on public.classeur_acces for insert to authenticated
  with check ((select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces update (gestion)" on public.classeur_acces;
create policy "classeur_acces update (gestion)"
  on public.classeur_acces for update to authenticated
  using ((select private.classeur_gestion_ok()))
  with check ((select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces delete (gestion)" on public.classeur_acces;
create policy "classeur_acces delete (gestion)"
  on public.classeur_acces for delete to authenticated
  using ((select private.classeur_gestion_ok()));

-- 6) Gardes sur le classeur : ce que la RLS « ligne » ne distingue pas --------
create or replace function private.classeur_garde()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Contexte système (CLI, service) : aucune garde.
  if auth.uid() is null or private.classeur_gestion_ok() then
    return new;
  end if;
  if tg_op = 'INSERT' then
    -- « Privé » à la création : réservé à la gestion.
    new.acces_tous := 'lecture';
    return new;
  end if;
  if new.acces_tous is distinct from old.acces_tous then
    raise exception 'Seule la gestion modifie l''accès d''un classeur.' using errcode = '42501';
  end if;
  if new.deleted_at is distinct from old.deleted_at then
    raise exception 'Seule la gestion supprime un classeur.' using errcode = '42501';
  end if;
  if new.sort_order is distinct from old.sort_order then
    raise exception 'Seule la gestion réordonne la liste des classeurs.' using errcode = '42501';
  end if;
  return new;
end;
$$;
revoke execute on function private.classeur_garde() from public, anon, authenticated;

drop trigger if exists classeur_garde on public.classeur_classeurs;
create trigger classeur_garde before insert or update on public.classeur_classeurs
  for each row execute function private.classeur_garde();

-- 7) Journal des accès ------------------------------------------------------------
drop trigger if exists audit_classeur_acces on public.classeur_acces;
create trigger audit_classeur_acces
  after insert or update or delete on public.classeur_acces
  for each row execute function private.log_row_change();

drop trigger if exists audit_classeur_acces_tous on public.classeur_classeurs;
create trigger audit_classeur_acces_tous
  after update of acces_tous on public.classeur_classeurs
  for each row when (old.acces_tous is distinct from new.acces_tous)
  execute function private.log_row_change();

-- 8) Personnes ayant accès à la page (pour le dialogue d'accès, gestion) -----
create or replace function private.classeur_personnes()
returns table (id uuid, prenom text, nom text, nom_affiche text, niveau_page text)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.classeur_gestion_ok() then
    raise exception 'Réservé à la gestion de la page Classeur.' using errcode = '42501';
  end if;
  return query
    select p.id, coalesce(p.first_name, ''), coalesce(p.last_name, ''),
           coalesce(p.display_name, ''),
           case when p.role = 'admin' then 'gestion' else u.level end
      from public.profiles p
      left join public.user_page_permissions u
        on u.user_id = p.id and u.page = 'classeur'
     where p.role = 'admin' or u.level is not null
     order by coalesce(nullif(p.last_name, ''), p.display_name), p.first_name;
end;
$$;
revoke execute on function private.classeur_personnes() from public, anon;
grant execute on function private.classeur_personnes() to authenticated, service_role;

create or replace function public.classeur_personnes()
returns table (id uuid, prenom text, nom text, nom_affiche text, niveau_page text)
language sql
stable
security invoker
set search_path = ''
as $$ select * from private.classeur_personnes(); $$;
revoke execute on function public.classeur_personnes() from public, anon;
grant execute on function public.classeur_personnes() to authenticated;


-- =============================================================================
-- 9) DURCISSEMENT (2026-09-28) — bloc IDENTIQUE à
--    classeur_securite_2026-09-28.sql (voir son en-tête pour le pourquoi).
--    DOIT rester APRÈS la section 8 : il remplace classeur_stamp (section 3)
--    et classeur_garde (section 8).
-- =============================================================================
-- 1) Identifiants : generated always ------------------------------------------
do $$
declare t text;
begin
  for t in
    select c.relname
      from pg_attribute a
      join pg_class c on c.oid = a.attrelid
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind = 'r'
       and c.relname like 'classeur\_%'
       and a.attname = 'id' and a.attidentity = 'd'
  loop
    execute format('alter table public.%I alter column id set generated always', t);
  end loop;
end $$;

-- 2) Estampillage : horodatages bornés au présent ------------------------------
create or replace function public.classeur_stamp()
returns trigger
language plpgsql
security invoker
set search_path to 'public'
as $function$
begin
  -- 2026-09-25 (classeur_stamp_updated_at_2026-09-25.sql) : un `updated_at`
  -- FOURNI par le client est respecté (fusion JSON : horodatage du fichier,
  -- règle « dernier écrit gagne ») ; sinon now(), comme avant.
  -- 2026-09-28 (classeur_securite_2026-09-28.sql) : jamais dans le futur
  -- (au-delà de 5 min de dérive d'horloge, ramené à now()).
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    if new.updated_at is null then
      new.updated_at := now();
    end if;
    if new.created_at > now() + interval '5 minutes' then
      new.created_at := now();
    end if;
  else
    new.created_by := private.keep_author(new.created_by, old.created_by);
    if new.updated_at is not distinct from old.updated_at then
      new.updated_at := now();
    end if;
  end if;
  if new.updated_at > now() + interval '5 minutes' then
    new.updated_at := now();
  end if;
  return new;
end;
$function$;
revoke execute on function public.classeur_stamp() from public, anon, authenticated;

-- 3) Garde du classeur : création rangée en fin de liste -----------------------
create or replace function private.classeur_garde()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Contexte système (CLI, service) : aucune garde.
  if auth.uid() is null or private.classeur_gestion_ok() then
    return new;
  end if;
  if tg_op = 'INSERT' then
    -- « Privé » à la création : réservé à la gestion.
    new.acces_tous := 'lecture';
    -- Ni créé supprimé, ni placé où l'on veut dans la liste PARTAGÉE
    -- (réordonner = gestion) : toujours en fin de liste.
    new.deleted_at := null;
    new.sort_order := coalesce(
      (select max(c.sort_order) from public.classeur_classeurs c), 0) + 1;
    return new;
  end if;
  if new.acces_tous is distinct from old.acces_tous then
    raise exception 'Seule la gestion modifie l''accès d''un classeur.' using errcode = '42501';
  end if;
  if new.deleted_at is distinct from old.deleted_at then
    raise exception 'Seule la gestion supprime un classeur.' using errcode = '42501';
  end if;
  if new.sort_order is distinct from old.sort_order then
    raise exception 'Seule la gestion réordonne la liste des classeurs.' using errcode = '42501';
  end if;
  return new;
end;
$$;
revoke execute on function private.classeur_garde() from public, anon, authenticated;

-- 4) Fiche image : chemin dans le dossier de SON classeur ----------------------
do $$ begin
  if not exists (select 1 from pg_constraint
                  where conname = 'classeur_images_chemin_du_classeur') then
    alter table public.classeur_images
      add constraint classeur_images_chemin_du_classeur
      check (split_part(chemin, '/', 1) = classeur_id::text);
  end if;
end $$;

-- 5) L'historique suit le document ------------------------------------------------
create or replace function private.classeur_versions_suivent()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_name = 'classeur_documents' then
    if new.chapter_id is distinct from old.chapter_id then
      update public.classeur_document_versions v
         set classeur_id = ch.classeur_id
        from public.classeur_chapters ch
       where ch.id = new.chapter_id
         and v.document_id = new.id
         and v.classeur_id is distinct from ch.classeur_id;
    end if;
  elsif new.classeur_id is distinct from old.classeur_id then
    update public.classeur_document_versions v
       set classeur_id = new.classeur_id
      from public.classeur_documents d
     where d.chapter_id = new.id
       and v.document_id = d.id
       and v.classeur_id is distinct from new.classeur_id;
  end if;
  return null;
end;
$$;
revoke execute on function private.classeur_versions_suivent() from public, anon, authenticated;

drop trigger if exists classeur_versions_suivent on public.classeur_documents;
create trigger classeur_versions_suivent
  after update of chapter_id on public.classeur_documents
  for each row execute function private.classeur_versions_suivent();
drop trigger if exists classeur_versions_suivent on public.classeur_chapters;
create trigger classeur_versions_suivent
  after update of classeur_id on public.classeur_chapters
  for each row execute function private.classeur_versions_suivent();

-- 6) search_path vide ----------------------------------------------------------------
alter function private.classeur_chapter_write_ok(bigint) set search_path = '';

commit;

-- =============================================================================
-- 6) VÉRIFICATION (lecture seule) — tout doit être `true`
-- =============================================================================
with tables as (
  select unnest(array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history', 'classeur_images'
  ]) as t
)
select controle, ok::text from (
  select 1 as n, '9 tables presentes' as controle,
    (select count(*) from pg_tables p join tables on p.tablename = tables.t where p.schemaname = 'public') = 9 as ok
  union all
  select 2, 'RLS activee sur les 9',
    (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace join tables on c.relname = tables.t
      where n.nspname = 'public' and c.relrowsecurity) = 9
  union all
  select 3, 'aucune policy to public sur classeur_*',
    (select count(*) from pg_policies where schemaname = 'public' and tablename like 'classeur\_%' and 'public' = any(roles)) = 0
  union all
  select 4, '9 policies read + 14 insert/update + 3 delete/insert historique = 26',
    (select count(*) from pg_policies where schemaname = 'public' and tablename like 'classeur\_%') = 26
  union all
  select 5, 'trigger classeur_stamp pose 8 fois (+ taille sur l historique)',
    (select count(*) from pg_trigger where tgname = 'classeur_stamp' and not tgisinternal) = 8
  union all
  select 6, 'classeur_stamp non executable par anon/authenticated/public',
    not has_function_privilege('anon', 'public.classeur_stamp()', 'execute')
    and not has_function_privilege('authenticated', 'public.classeur_stamp()', 'execute')
  union all
  select 7, 'anon sans privilege sur les 9 tables',
    (select count(*) from information_schema.role_table_grants g join tables on g.table_name = tables.t
      where g.grantee = 'anon' and g.table_schema = 'public') = 0
  union all
  select 8, '9 periodicites',
    (select count(*) from public.classeur_periodicites) = 9
  union all
  select 9, 'aucune fonction security definer classeur_* dans public',
    (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname like 'classeur\_%' and p.prosecdef) = 0
) v order by n;
