-- =============================================================================
-- classeur_versions_documents_2026-09-27.sql — HISTORIQUE des documents du
-- Classeur (améliorations n° 20 et 21 de plan/classeur-editeur-ameliorations).
--
-- Application : `supabase db query --linked -f supabase/classeur_versions_documents_2026-09-27.sql`
-- L'autorité `classeur_2026-09-25.sql` porte le même bloc (section 6) :
-- rejouer l'un ou l'autre donne le même résultat.
--
-- Demande utilisateur (2026-09-27) : « voir les anciennes versions d'une
--   procédure, qui et quand, pouvoir en restaurer une » (20) et « comparer
--   deux versions, comme GitHub » (21).
--
-- Modèle : une ligne = l'état COMPLET d'un document (titre, description,
--   texte) après un enregistrement. Écrite par un TRIGGER après chaque
--   insert/update qui change le titre, la description ou le texte — quel
--   que soit l'écran ou le chemin (éditeur, fusion JSON, restauration,
--   retrait d'une image supprimée) : rien ne peut l'oublier.
--   - Premier enregistrement suivi d'un document existant : l'état D'AVANT
--     est d'abord conservé (`origine = 'etat_initial'`, date = son
--     `updated_at`), sinon la première modification serait incomparable.
--   - L'auteur est FIGÉ en clair (`auteur`, prénom nom ou nom affiché) :
--     les lecteurs n'ont pas le droit de lire les profils des autres, et le
--     nom reste juste si le compte est supprimé (`created_by` → null).
--     Jamais l'adresse e-mail.
--   - Borne : les 50 dernières versions par document (texte seul, ~3 ko en
--     moyenne ici : 45 documents × 50 ≈ 7 Mo au pire).
--
-- RLS : lecture rang >= 1 (comme les documents) ; AUCUN droit d'écriture
--   pour `authenticated` (ni grant ni policy) : seul le trigger écrit.
--   Restaurer une version = la recharger dans l'éditeur puis enregistrer
--   (écriture normale du document, qui crée elle-même une version).
--
-- Innocuité : create table if not exists, fonction et trigger recréés,
--   policies drop/create. Aucune donnée existante n'est modifiée. Le seul
--   `delete` est la borne des 50 versions, ciblée sur UN document.
-- =============================================================================

begin;

create table if not exists public.classeur_document_versions (
  id           bigint generated by default as identity primary key,
  document_id  bigint      not null references public.classeur_documents(id) on delete cascade,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  title        text        not null default '',
  description  text        not null default '',
  content      text        not null default '',
  origine      text        not null default 'enregistrement'
                           check (origine in ('creation', 'enregistrement', 'etat_initial')),
  auteur       text        not null default '',
  created_by   uuid        references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists classeur_document_versions_doc_idx
  on public.classeur_document_versions (document_id, created_at desc, id desc);

create or replace function private.classeur_document_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_classeur bigint;
  v_uid      uuid := auth.uid();
  v_auteur   text := '';
begin
  if tg_op = 'UPDATE'
     and new.title is not distinct from old.title
     and new.description is not distinct from old.description
     and new.content is not distinct from old.content then
    return null;
  end if;

  select ch.classeur_id into v_classeur
    from public.classeur_chapters ch where ch.id = new.chapter_id;
  if v_classeur is null then
    return null;
  end if;

  if v_uid is not null then
    select coalesce(
             nullif(btrim(coalesce(p.first_name, '') || ' ' || coalesce(p.last_name, '')), ''),
             nullif(btrim(p.display_name), ''),
             '')
      into v_auteur
      from public.profiles p where p.id = v_uid;
  end if;

  -- État d'avant le suivi : conservé une fois, au premier enregistrement.
  if tg_op = 'UPDATE' and not exists (
       select 1 from public.classeur_document_versions v where v.document_id = new.id) then
    insert into public.classeur_document_versions
      (document_id, classeur_id, title, description, content, origine, auteur, created_by, created_at)
    values
      (old.id, v_classeur, old.title, old.description, old.content, 'etat_initial', '', null, old.updated_at);
  end if;

  insert into public.classeur_document_versions
    (document_id, classeur_id, title, description, content, origine, auteur, created_by)
  values
    (new.id, v_classeur, new.title, new.description, new.content,
     case tg_op when 'INSERT' then 'creation' else 'enregistrement' end,
     coalesce(v_auteur, ''), v_uid);

  -- Borne : 50 versions par document, les plus récentes.
  delete from public.classeur_document_versions v
   where v.document_id = new.id
     and v.id not in (
       select w.id from public.classeur_document_versions w
        where w.document_id = new.id
        order by w.created_at desc, w.id desc
        limit 50);

  return null;
end;
$$;
revoke execute on function private.classeur_document_version() from public, anon, authenticated;

drop trigger if exists classeur_document_version on public.classeur_documents;
create trigger classeur_document_version
  after insert or update of title, description, content on public.classeur_documents
  for each row execute function private.classeur_document_version();

-- Privilèges : anon rien ; authenticated LECTURE seule, sous RLS.
revoke all on table public.classeur_document_versions from public, anon, authenticated;
grant select on table public.classeur_document_versions to authenticated;
alter table public.classeur_document_versions enable row level security;
revoke all on sequence public.classeur_document_versions_id_seq from public, anon, authenticated;

drop policy if exists "classeur_document_versions read (page:classeur)" on public.classeur_document_versions;
create policy "classeur_document_versions read (page:classeur)"
  on public.classeur_document_versions for select to authenticated
  -- Depuis le 2026-09-28 : niveau effectif sur le classeur (classeur_acces_2026-09-28.sql).
  using ((select private.classeur_lecture_ok(classeur_id)));

commit;

-- Vérification (lecture seule) --------------------------------------------------
select 'table classeur_document_versions, RLS activee' as controle,
       ((select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = 'public' and c.relname = 'classeur_document_versions' and c.relrowsecurity) = 1)::text as ok
union all
select 'une seule policy, en lecture',
       ((select count(*) from pg_policies where tablename = 'classeur_document_versions') = 1
        and (select count(*) from pg_policies where tablename = 'classeur_document_versions' and cmd = 'SELECT') = 1)::text
union all
select 'authenticated : select seul ; anon : rien',
       ((select string_agg(privilege_type, ',' order by privilege_type) from information_schema.role_table_grants
          where grantee = 'authenticated' and table_schema = 'public' and table_name = 'classeur_document_versions') = 'SELECT'
        and (select count(*) from information_schema.role_table_grants
          where grantee = 'anon' and table_schema = 'public' and table_name = 'classeur_document_versions') = 0)::text
union all
select 'trigger pose sur classeur_documents',
       ((select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid
          where c.relname = 'classeur_documents' and t.tgname = 'classeur_document_version' and not t.tgisinternal) = 1)::text
union all
select 'fonction trigger definer dans private, fermee a authenticated',
       ((select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
          where n.nspname = 'private' and p.proname = 'classeur_document_version' and p.prosecdef
            and not has_function_privilege('authenticated', p.oid, 'execute')) = 1)::text;
