-- =============================================================================
-- REMPLACÉ — NE PLUS REJOUER (audit de sécurité du 2026-09-28).
-- Rejoué, il rouvrirait la lecture de la médiathèque de TOUS les classeurs
-- (privés compris) au seul rang de page.
-- Autorité : classeur_2026-09-25.sql (sections 8 et 9). Contrôle :
-- verif_classeur_acces.sql (échoue si ce fichier a été rejoué).
-- =============================================================================
-- =============================================================================
-- classeur_images_table_2026-09-26.sql — MÉDIATHÈQUE d'un classeur : la
-- table `classeur_images` qui décrit chaque image du bucket.
--
-- Application : `supabase db query --linked -f supabase/classeur_images_table_2026-09-26.sql`
-- L'autorité `classeur_2026-09-25.sql` porte la même table (sections 1, 3,
-- 4, 5) : rejouer l'un ou l'autre donne le même résultat.
--
-- Demande utilisateur (2026-09-26) : « si elles sont dans le bucket, je ne
--   les vois pas… un système de rangement à plusieurs niveaux : une image
--   dans un classeur, utilisable dans plusieurs chapitres ; dans un
--   document, voir les images du document ou du classeur ».
--
-- Modèle : une image appartient au CLASSEUR (`classeur_id`), pas à un
--   document — un document la référence par son chemin dans son Markdown,
--   plusieurs documents peuvent référencer la même. L'usage (quels
--   documents) est CALCULÉ par l'app depuis les contenus, jamais stocké :
--   rien à tenir à jour, jamais faux. Suppression douce (`deleted_at`),
--   le fichier du bucket est retiré par l'app avant de marquer la fiche.
--
-- RLS (mêmes règles que le contenu) : lecture rang >= 1 ; insert/update
--   par `private.classeur_write_ok(classeur_id)` (gestion, ou écriture ET
--   propriétaire) ; pas de delete physique.
--
-- Innocuité : create table if not exists, policies drop/create, trigger
--   d'estampillage `classeur_stamp` (existant). Aucune donnée touchée.
-- =============================================================================

begin;

create table if not exists public.classeur_images (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  chemin       text        not null unique
                           check (chemin ~ '^[0-9]{1,12}/[0-9a-f-]{36}\.webp$'),
  nom          text        not null default '',
  taille       integer     not null default 0 check (taille >= 0),
  largeur      integer     not null default 0 check (largeur >= 0),
  hauteur      integer     not null default 0 check (hauteur >= 0),
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_images_classeur_idx
  on public.classeur_images (classeur_id, created_at desc) where deleted_at is null;

-- Estampillage (created_by posé/figé, updated_at) : trigger existant.
drop trigger if exists classeur_stamp on public.classeur_images;
create trigger classeur_stamp before insert or update on public.classeur_images
  for each row execute function public.classeur_stamp();

-- Privilèges : anon rien ; authenticated DML sous RLS.
revoke all on table public.classeur_images from public, anon;
grant select, insert, update, delete on table public.classeur_images to authenticated;
alter table public.classeur_images enable row level security;
revoke all on sequence public.classeur_images_id_seq from public, anon;
grant usage, select on sequence public.classeur_images_id_seq to authenticated;

drop policy if exists "classeur_images read (page:classeur)" on public.classeur_images;
create policy "classeur_images read (page:classeur)"
  on public.classeur_images for select to authenticated
  using ((select private.page_level_rank(private.get_page_level('classeur'))) >= 1);

drop policy if exists "classeur_images insert (page:classeur)" on public.classeur_images;
create policy "classeur_images insert (page:classeur)"
  on public.classeur_images for insert to authenticated
  with check ((select private.classeur_write_ok(classeur_id)));

drop policy if exists "classeur_images update (page:classeur)" on public.classeur_images;
create policy "classeur_images update (page:classeur)"
  on public.classeur_images for update to authenticated
  using ((select private.classeur_write_ok(classeur_id)))
  with check ((select private.classeur_write_ok(classeur_id)));

commit;

-- Vérification (lecture seule) --------------------------------------------------
select 'table classeur_images, RLS activee' as controle,
       ((select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
          where n.nspname = 'public' and c.relname = 'classeur_images' and c.relrowsecurity) = 1)::text as ok
union all
select '3 policies (read, insert, update), aucune delete',
       ((select count(*) from pg_policies where tablename = 'classeur_images') = 3
        and (select count(*) from pg_policies where tablename = 'classeur_images' and cmd = 'DELETE') = 0)::text
union all
select 'insert/update par proprietaire',
       ((select count(*) from pg_policies where tablename = 'classeur_images'
           and cmd in ('INSERT', 'UPDATE')
           and (coalesce(qual, '') || coalesce(with_check, '')) like '%classeur_write_ok%') = 2)::text
union all
select 'trigger classeur_stamp pose',
       ((select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid
          where c.relname = 'classeur_images' and t.tgname = 'classeur_stamp' and not t.tgisinternal) = 1)::text
union all
select 'anon sans privilege',
       ((select count(*) from information_schema.role_table_grants
          where grantee = 'anon' and table_schema = 'public' and table_name = 'classeur_images') = 0)::text
union all
select 'chemin unique et borne au format du bucket',
       ((select count(*) from pg_constraint where conrelid = 'public.classeur_images'::regclass
          and contype in ('u', 'c') and pg_get_constraintdef(oid) like '%chemin%') = 2)::text;
