-- =============================================================================
-- classeur_2026-09-25.sql — page « Classeur » : schéma complet (portage de
-- l'application de bureau Registre, github.com/Owltus/Registre).
--
-- Application : `supabase db query --linked -f supabase/classeur_2026-09-25.sql`
-- AUTORITÉ UNIQUE pour toutes les tables `classeur_*` : rejouable (idempotent),
-- à faire évoluer ICI (jamais de DDL à la volée).
--
-- Contexte : Registre stockait ces données dans un SQLite local (7 tables +
--   historique de fusion). Le Back Office les porte dans Postgres avec les
--   pratiques du projet : RLS par page à trois niveaux, estampillage d'auteur
--   par trigger via private.keep_author, aucun privilège pour anon, aucune
--   fonction security definer dans public.
--
-- Modèle :
--   classeur_classeurs        conteneur (nom, icône Lucide, établissement)
--   classeur_chapters         chapitre d'un classeur
--   classeur_periodicites     référentiel des périodicités de suivi (seed)
--   classeur_documents        document Markdown d'un chapitre
--   classeur_tracking_sheets  feuille de suivi périodique
--   classeur_signature_sheets feuille d'émargement (N lignes)
--   classeur_intercalaires    page de séparation
--   classeur_merge_history    instantanés JSON pris avant chaque fusion
--
-- Droits (plan/page-classeur/00-INDEX.md) :
--   lecture  (rang 1) : tout lire, imprimer.
--   ecriture (rang 2) : créer, modifier, réordonner, supprimer (douce),
--                       importer, fusionner (insert dans l'historique).
--   gestion           : suppression PHYSIQUE d'un classeur ou d'une entrée
--                       d'historique (tout le reste est une suppression douce
--                       = update de deleted_at).
--   Aucune fenêtre de grâce : un classeur réglementaire n'a pas de « jour ».
--
-- Innocuité : create table if not exists, create or replace, drop policy if
--   exists puis create. Ne touche à aucune table existante. Aucune donnée
--   réécrite. Le seed des périodicités est protégé par `on conflict do nothing`
--   sur le libellé.
--
-- Vérification : section finale (lecture seule), tout doit être `true`.
-- =============================================================================

begin;

-- =============================================================================
-- 1) TABLES
-- =============================================================================

create table if not exists public.classeur_classeurs (
  id                        bigint generated by default as identity primary key,
  uuid                      uuid        not null default gen_random_uuid() unique,
  name                      text        not null default 'Mon classeur',
  icon                      text        not null default 'BookOpen',
  etablissement             text        not null default '',
  etablissement_complement  text        not null default '',
  sort_order                integer     not null default 0,
  deleted_at                timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  created_by                uuid        references public.profiles(id) on delete set null
);

create table if not exists public.classeur_chapters (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  label        text        not null,
  icon         text        not null default 'FileText',
  description  text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_chapters_classeur_idx
  on public.classeur_chapters (classeur_id) where deleted_at is null;

create table if not exists public.classeur_periodicites (
  id          bigint  generated by default as identity primary key,
  label       text    not null unique,
  nombre      integer not null default 8,
  sort_order  integer not null default 0
);

create table if not exists public.classeur_documents (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  content      text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_documents_chapter_idx
  on public.classeur_documents (chapter_id) where deleted_at is null;

create table if not exists public.classeur_tracking_sheets (
  id              bigint generated by default as identity primary key,
  uuid            uuid        not null default gen_random_uuid() unique,
  chapter_id      bigint      not null references public.classeur_chapters(id) on delete cascade,
  title           text        not null,
  periodicite_id  bigint      not null references public.classeur_periodicites(id),
  sort_order      integer     not null default 0,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  created_by      uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_tracking_sheets_chapter_idx
  on public.classeur_tracking_sheets (chapter_id) where deleted_at is null;

create table if not exists public.classeur_signature_sheets (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  nombre       integer     not null default 14 check (nombre between 1 and 60),
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_signature_sheets_chapter_idx
  on public.classeur_signature_sheets (chapter_id) where deleted_at is null;

create table if not exists public.classeur_intercalaires (
  id           bigint generated by default as identity primary key,
  uuid         uuid        not null default gen_random_uuid() unique,
  chapter_id   bigint      not null references public.classeur_chapters(id) on delete cascade,
  title        text        not null,
  description  text        not null default '',
  sort_order   integer     not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
create index if not exists classeur_intercalaires_chapter_idx
  on public.classeur_intercalaires (chapter_id) where deleted_at is null;

create table if not exists public.classeur_merge_history (
  id           bigint generated by default as identity primary key,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  merged_at    timestamptz not null default now(),
  source_name  text        not null default '',
  inserted     integer     not null default 0,
  updated      integer     not null default 0,
  unchanged    integer     not null default 0,
  skipped      integer     not null default 0,
  snapshot     jsonb       not null,
  -- 2026-09-26 (classeur_points_restauration_2026-09-26.sql) : points de
  -- restauration mineurs/majeurs. kind : auto | manuel | fusion | securite.
  kind         text        not null default 'fusion'
                           check (kind in ('auto', 'manuel', 'fusion', 'securite')),
  label        text        not null default '',
  taille       integer,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null
);
alter table public.classeur_merge_history
  add column if not exists kind text not null default 'fusion'
    check (kind in ('auto', 'manuel', 'fusion', 'securite')),
  add column if not exists label text not null default '',
  add column if not exists taille integer;
create index if not exists classeur_merge_history_classeur_idx
  on public.classeur_merge_history (classeur_id, merged_at desc);
create index if not exists classeur_merge_history_kind_idx
  on public.classeur_merge_history (classeur_id, kind, merged_at desc);

-- Poids de l'instantané, posé à l'insertion (affiché dans le dialogue).
create or replace function public.classeur_merge_history_taille()
returns trigger
language plpgsql
security invoker
set search_path to 'public'
as $function$
begin
  new.taille := pg_column_size(new.snapshot);
  return new;
end;
$function$;
revoke execute on function public.classeur_merge_history_taille() from public, anon, authenticated;
drop trigger if exists classeur_merge_history_taille on public.classeur_merge_history;
create trigger classeur_merge_history_taille
  before insert on public.classeur_merge_history
  for each row execute function public.classeur_merge_history_taille();

-- =============================================================================
-- 2) SEED — périodicités (identique à Registre ; `nombre` = colonnes du tableau)
-- =============================================================================
insert into public.classeur_periodicites (label, nombre, sort_order) values
  ('Mensuel',        8, 1),
  ('Sesquimestriel', 8, 2),
  ('Semestriel',     8, 3),
  ('Annuel',         8, 4),
  ('Biennale',       8, 5),
  ('Triennal',       4, 6),
  ('Quadriennal',    4, 7),
  ('Quinquennal',    4, 8),
  ('Non défini',     8, 9)
on conflict (label) do nothing;

-- =============================================================================
-- 3) ESTAMPILLAGE — une fonction trigger pour les 7 tables (invoker, fermée)
-- =============================================================================
create or replace function public.classeur_stamp()
returns trigger
language plpgsql
security invoker
set search_path to 'public'
as $function$
begin
  -- 2026-09-25 (classeur_stamp_updated_at_2026-09-25.sql) : un `updated_at`
  -- FOURNI par le client est respecté (fusion JSON : horodatage du fichier,
  -- règle « dernier écrit gagne ») ; sinon now(), comme avant.
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    if new.updated_at is null then
      new.updated_at := now();
    end if;
  else
    new.created_by := private.keep_author(new.created_by, old.created_by);
    if new.updated_at is not distinct from old.updated_at then
      new.updated_at := now();
    end if;
  end if;
  return new;
end;
$function$;
revoke execute on function public.classeur_stamp() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_documents',
    'classeur_tracking_sheets', 'classeur_signature_sheets',
    'classeur_intercalaires', 'classeur_merge_history'
  ] loop
    execute format('drop trigger if exists classeur_stamp on public.%I', t);
    execute format(
      'create trigger classeur_stamp before insert or update on public.%I
         for each row execute function public.classeur_stamp()', t);
  end loop;
end $$;

-- =============================================================================
-- 4) PRIVILÈGES — anon : rien ; authenticated : DML sous RLS
-- =============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history'
  ] loop
    execute format('revoke all on table public.%I from public, anon', t);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on sequence public.%I_id_seq from public, anon', t);
    execute format('grant usage, select on sequence public.%I_id_seq to authenticated', t);
  end loop;
end $$;

-- =============================================================================
-- 5) RLS — modèle literie.sql, appels enveloppés en (select …)
-- =============================================================================

-- Lecture : rang >= 1 sur les 8 tables.
do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.page_level_rank(private.get_page_level(''classeur''))) >= 1)', t, t);
  end loop;
end $$;

-- Écriture (insert + update) : rang >= 2 sur les 6 tables de contenu.
-- La suppression douce est un update : elle passe par ici.
do $$
declare t text;
begin
  foreach t in array array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_documents',
    'classeur_tracking_sheets', 'classeur_signature_sheets',
    'classeur_intercalaires'
  ] loop
    execute format('drop policy if exists "%s insert (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s insert (page:classeur)" on public.%I for insert to authenticated
         with check ((select private.page_level_rank(private.get_page_level(''classeur''))) >= 2)', t, t);
    execute format('drop policy if exists "%s update (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s update (page:classeur)" on public.%I for update to authenticated
         using ((select private.page_level_rank(private.get_page_level(''classeur''))) >= 2)
         with check ((select private.page_level_rank(private.get_page_level(''classeur''))) >= 2)', t, t);
  end loop;
end $$;

-- Suppression PHYSIQUE d'un classeur : gestion seule (les enfants suivent par
-- cascade). Les chapitres et éléments n'ont PAS de policy delete : leur
-- suppression est douce.
drop policy if exists "classeur_classeurs delete (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs delete (page:classeur)"
  on public.classeur_classeurs for delete to authenticated
  using ((select private.get_page_level('classeur')) = 'gestion');

-- Historique de fusion : l'instantané est écrit par qui fusionne (rang >= 2) ;
-- jamais modifié ; purgé par la gestion seule.
drop policy if exists "classeur_merge_history insert (page:classeur)" on public.classeur_merge_history;
create policy "classeur_merge_history insert (page:classeur)"
  on public.classeur_merge_history for insert to authenticated
  with check ((select private.page_level_rank(private.get_page_level('classeur'))) >= 2);

-- 2026-09-26 : un point AUTO (mineur) est élagué par qui l'écrit (rang >= 2),
-- sinon l'historique d'un compte `ecriture` grandirait sans borne ; les
-- points majeurs restent réservés à `gestion`.
drop policy if exists "classeur_merge_history delete (page:classeur)" on public.classeur_merge_history;
create policy "classeur_merge_history delete (page:classeur)"
  on public.classeur_merge_history for delete to authenticated
  using (
    (select private.get_page_level('classeur')) = 'gestion'
    or (
      kind = 'auto'
      and (select private.page_level_rank(private.get_page_level('classeur'))) >= 2
    )
  );

commit;

-- =============================================================================
-- 6) VÉRIFICATION (lecture seule) — tout doit être `true`
-- =============================================================================
with tables as (
  select unnest(array[
    'classeur_classeurs', 'classeur_chapters', 'classeur_periodicites',
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires',
    'classeur_merge_history'
  ]) as t
)
select controle, ok::text from (
  select 1 as n, '8 tables presentes' as controle,
    (select count(*) from pg_tables p join tables on p.tablename = tables.t where p.schemaname = 'public') = 8 as ok
  union all
  select 2, 'RLS activee sur les 8',
    (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace join tables on c.relname = tables.t
      where n.nspname = 'public' and c.relrowsecurity) = 8
  union all
  select 3, 'aucune policy to public sur classeur_*',
    (select count(*) from pg_policies where schemaname = 'public' and tablename like 'classeur\_%' and 'public' = any(roles)) = 0
  union all
  select 4, '8 policies read + 12 insert/update + 3 delete/insert historique = 23',
    (select count(*) from pg_policies where schemaname = 'public' and tablename like 'classeur\_%') = 23
  union all
  select 5, 'trigger classeur_stamp pose 7 fois (+ taille sur l historique)',
    (select count(*) from pg_trigger where tgname = 'classeur_stamp' and not tgisinternal) = 7
  union all
  select 6, 'classeur_stamp non executable par anon/authenticated/public',
    not has_function_privilege('anon', 'public.classeur_stamp()', 'execute')
    and not has_function_privilege('authenticated', 'public.classeur_stamp()', 'execute')
  union all
  select 7, 'anon sans privilege sur les 8 tables',
    (select count(*) from information_schema.role_table_grants g join tables on g.table_name = tables.t
      where g.grantee = 'anon' and g.table_schema = 'public') = 0
  union all
  select 8, '9 periodicites',
    (select count(*) from public.classeur_periodicites) = 9
  union all
  select 9, 'aucune fonction security definer classeur_* dans public',
    (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname like 'classeur\_%' and p.prosecdef) = 0
) v order by n;
