-- =============================================================================
-- classeur_acces_2026-09-28.sql — ACCÈS PAR CLASSEUR (des droits dans les
-- droits de page). Plan : plan/classeur-acces-par-classeur/ (étapes 1 et 2).
--
-- Application : `supabase db query --linked -f supabase/classeur_acces_2026-09-28.sql`
-- Contrôle    : `supabase db query --linked -f supabase/verif_classeur_acces.sql`
-- L'autorité `classeur_2026-09-25.sql` porte le même bloc (section 8).
--
-- Règle (validée par l'utilisateur le 2026-09-28) :
--   niveau effectif = le plus petit de (droit sur la PAGE, droit sur le
--   CLASSEUR) ; gestion de la page et admin : tout.
--   Droit sur le classeur, par priorité : exception de la personne
--   (aucun / lecture / ecriture, dans les DEUX sens, créateur compris),
--   sinon créateur → ecriture, sinon l'accès pour tous du classeur.
--
-- Réservé à la gestion / admin, même pour l'écriture : gérer les accès,
--   supprimer un classeur (douce ou physique), réordonner la LISTE des
--   classeurs, créer un classeur « privé » (forcé à lecture pour tous
--   sinon). Restaurer un point et vider l'historique : bloqués en interface
--   (une restauration n'est qu'une suite d'écritures ordinaires).
--
-- Sécurité en base PARTOUT : la lecture de chaque table de contenu (et des
--   fichiers du stockage) passe par le niveau effectif — un classeur masqué
--   ne doit pas rester lisible par ses images, sa médiathèque, ses points de
--   restauration (copies complètes) ou l'historique de ses documents.
--
-- Bascule : colonne `acces_tous` avec défaut `lecture` → les classeurs
--   existants restent lisibles par tous ceux qui ont la page (aujourd'hui :
--   l'admin seul).
--
-- Innocuité : ajout d'une colonne à défaut, d'une table, de fonctions ;
--   policies drop/create ; aucune donnée existante réécrite ni supprimée.
-- =============================================================================

begin;

-- 1) Accès pour tous ----------------------------------------------------------
alter table public.classeur_classeurs
  add column if not exists acces_tous text not null default 'lecture';
do $$ begin
  if not exists (select 1 from pg_constraint
                  where conname = 'classeur_classeurs_acces_tous_check') then
    alter table public.classeur_classeurs
      add constraint classeur_classeurs_acces_tous_check
      check (acces_tous in ('aucun', 'lecture', 'ecriture'));
  end if;
end $$;

-- 2) Exceptions par personne ----------------------------------------------------
create table if not exists public.classeur_acces (
  id           bigint generated by default as identity primary key,
  classeur_id  bigint      not null references public.classeur_classeurs(id) on delete cascade,
  user_id      uuid        not null references public.profiles(id) on delete cascade,
  niveau       text        not null check (niveau in ('aucun', 'lecture', 'ecriture')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid        references public.profiles(id) on delete set null,
  unique (classeur_id, user_id)
);
create index if not exists classeur_acces_user_idx on public.classeur_acces (user_id);

drop trigger if exists classeur_stamp on public.classeur_acces;
create trigger classeur_stamp before insert or update on public.classeur_acces
  for each row execute function public.classeur_stamp();

revoke all on table public.classeur_acces from public, anon;
grant select, insert, update, delete on table public.classeur_acces to authenticated;
alter table public.classeur_acces enable row level security;
revoke all on sequence public.classeur_acces_id_seq from public, anon;
grant usage, select on sequence public.classeur_acces_id_seq to authenticated;

-- 3) Le niveau effectif : UNE fonction, source de vérité ------------------------
-- Calcul À PARTIR DES VALEURS DE LA LIGNE : la policy de lecture de
-- `classeur_classeurs` l'appelle avec les colonnes de la ligne elle-même.
-- Une création relit la ligne insérée (`insert … returning`), invisible à
-- une recherche par identifiant pendant l'insertion : chercher la ligne par
-- `id` refusait toute création (trouvé à la répétition du 2026-09-28).
create or replace function private.classeur_niveau_de(
  p_classeur_id bigint, p_created_by uuid, p_acces_tous text)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_page   text := private.get_page_level('classeur');
  v_uid    uuid := auth.uid();
  v_droit  text;
begin
  if v_page is null then
    return 'aucun';
  end if;
  if v_page = 'gestion' then
    return 'gestion';
  end if;
  v_droit := coalesce(
    (select a.niveau from public.classeur_acces a
      where a.classeur_id = p_classeur_id and a.user_id = v_uid),
    case when p_created_by = v_uid then 'ecriture' end,
    p_acces_tous);
  if v_droit is null or v_droit = 'aucun' then
    return 'aucun';
  end if;
  -- Plafond : le droit de page borne le droit sur le classeur.
  if v_page = 'lecture' then
    return 'lecture';
  end if;
  if v_page = 'ecriture' then
    return v_droit;
  end if;
  return 'aucun';
end;
$$;

-- Par identifiant : pour les tables enfants (chapitres, éléments, images…).
create or replace function private.classeur_niveau(p_classeur_id bigint)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when private.get_page_level('classeur') is not distinct from 'gestion' then 'gestion'
    else coalesce(
      (select private.classeur_niveau_de(c.id, c.created_by, c.acces_tous)
         from public.classeur_classeurs c where c.id = p_classeur_id),
      'aucun')
  end;
$$;

create or replace function private.classeur_lecture_ligne(
  p_classeur_id bigint, p_created_by uuid, p_acces_tous text)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau_de(p_classeur_id, p_created_by, p_acces_tous)
               in ('lecture', 'ecriture', 'gestion'); $$;

create or replace function private.classeur_lecture_ok(p_classeur_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau(p_classeur_id) in ('lecture', 'ecriture', 'gestion'); $$;

-- Même nom, même signature qu'avant : les policies d'écriture existantes
-- (chapitres, éléments, médiathèque, points, stockage) suivent seules.
create or replace function private.classeur_write_ok(p_classeur_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$ select private.classeur_niveau(p_classeur_id) in ('ecriture', 'gestion'); $$;

create or replace function private.classeur_chapter_read_ok(p_chapter_id bigint)
returns boolean language sql stable security definer set search_path = ''
as $$
  select coalesce(
    (select private.classeur_lecture_ok(ch.classeur_id)
       from public.classeur_chapters ch where ch.id = p_chapter_id),
    false);
$$;

create or replace function private.classeur_gestion_ok()
returns boolean language sql stable security definer set search_path = ''
as $$ select private.get_page_level('classeur') is not distinct from 'gestion'; $$;

do $$
declare f text;
begin
  foreach f in array array[
    'private.classeur_niveau_de(bigint, uuid, text)', 'private.classeur_niveau(bigint)',
    'private.classeur_lecture_ligne(bigint, uuid, text)', 'private.classeur_lecture_ok(bigint)',
    'private.classeur_write_ok(bigint)', 'private.classeur_chapter_read_ok(bigint)',
    'private.classeur_chapter_write_ok(bigint)', 'private.classeur_gestion_ok()'
  ] loop
    execute format('revoke execute on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated, service_role', f);
  end loop;
end $$;

-- 4) Lecture : le niveau effectif partout ---------------------------------------
drop policy if exists "classeur_classeurs read (page:classeur)" on public.classeur_classeurs;
create policy "classeur_classeurs read (page:classeur)"
  on public.classeur_classeurs for select to authenticated
  using (private.classeur_lecture_ligne(id, created_by, acces_tous));

do $$
declare t text;
begin
  foreach t in array array[
    'classeur_chapters', 'classeur_merge_history', 'classeur_images',
    'classeur_document_versions'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.classeur_lecture_ok(classeur_id)))', t, t);
  end loop;
  foreach t in array array[
    'classeur_documents', 'classeur_tracking_sheets',
    'classeur_signature_sheets', 'classeur_intercalaires'
  ] loop
    execute format('drop policy if exists "%s read (page:classeur)" on public.%I', t, t);
    execute format(
      'create policy "%s read (page:classeur)" on public.%I for select to authenticated
         using ((select private.classeur_chapter_read_ok(chapter_id)))', t, t);
  end loop;
end $$;

drop policy if exists "classeur-images read (page:classeur)" on storage.objects;
create policy "classeur-images read (page:classeur)"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'classeur-images'
    and array_length(storage.foldername(name), 1) = 1
    and (storage.foldername(name))[1] ~ '^[0-9]{1,12}$'
    and (select private.classeur_lecture_ok(((storage.foldername(name))[1])::bigint))
  );

-- 5) Exceptions : chacun lit les siennes, la gestion gère tout ----------------
drop policy if exists "classeur_acces read" on public.classeur_acces;
create policy "classeur_acces read"
  on public.classeur_acces for select to authenticated
  using (user_id = (select auth.uid()) or (select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces insert (gestion)" on public.classeur_acces;
create policy "classeur_acces insert (gestion)"
  on public.classeur_acces for insert to authenticated
  with check ((select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces update (gestion)" on public.classeur_acces;
create policy "classeur_acces update (gestion)"
  on public.classeur_acces for update to authenticated
  using ((select private.classeur_gestion_ok()))
  with check ((select private.classeur_gestion_ok()));

drop policy if exists "classeur_acces delete (gestion)" on public.classeur_acces;
create policy "classeur_acces delete (gestion)"
  on public.classeur_acces for delete to authenticated
  using ((select private.classeur_gestion_ok()));

-- 6) Gardes sur le classeur : ce que la RLS « ligne » ne distingue pas --------
create or replace function private.classeur_garde()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Contexte système (CLI, service) : aucune garde.
  if auth.uid() is null or private.classeur_gestion_ok() then
    return new;
  end if;
  if tg_op = 'INSERT' then
    -- « Privé » à la création : réservé à la gestion.
    new.acces_tous := 'lecture';
    return new;
  end if;
  if new.acces_tous is distinct from old.acces_tous then
    raise exception 'Seule la gestion modifie l''accès d''un classeur.' using errcode = '42501';
  end if;
  if new.deleted_at is distinct from old.deleted_at then
    raise exception 'Seule la gestion supprime un classeur.' using errcode = '42501';
  end if;
  if new.sort_order is distinct from old.sort_order then
    raise exception 'Seule la gestion réordonne la liste des classeurs.' using errcode = '42501';
  end if;
  return new;
end;
$$;
revoke execute on function private.classeur_garde() from public, anon, authenticated;

drop trigger if exists classeur_garde on public.classeur_classeurs;
create trigger classeur_garde before insert or update on public.classeur_classeurs
  for each row execute function private.classeur_garde();

-- 7) Journal des accès ------------------------------------------------------------
drop trigger if exists audit_classeur_acces on public.classeur_acces;
create trigger audit_classeur_acces
  after insert or update or delete on public.classeur_acces
  for each row execute function private.log_row_change();

drop trigger if exists audit_classeur_acces_tous on public.classeur_classeurs;
create trigger audit_classeur_acces_tous
  after update of acces_tous on public.classeur_classeurs
  for each row when (old.acces_tous is distinct from new.acces_tous)
  execute function private.log_row_change();

-- 8) Personnes ayant accès à la page (pour le dialogue d'accès, gestion) -----
create or replace function private.classeur_personnes()
returns table (id uuid, prenom text, nom text, nom_affiche text, niveau_page text)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.classeur_gestion_ok() then
    raise exception 'Réservé à la gestion de la page Classeur.' using errcode = '42501';
  end if;
  return query
    select p.id, coalesce(p.first_name, ''), coalesce(p.last_name, ''),
           coalesce(p.display_name, ''),
           case when p.role = 'admin' then 'gestion' else u.level end
      from public.profiles p
      left join public.user_page_permissions u
        on u.user_id = p.id and u.page = 'classeur'
     where p.role = 'admin' or u.level is not null
     order by coalesce(nullif(p.last_name, ''), p.display_name), p.first_name;
end;
$$;
revoke execute on function private.classeur_personnes() from public, anon;
grant execute on function private.classeur_personnes() to authenticated, service_role;

create or replace function public.classeur_personnes()
returns table (id uuid, prenom text, nom text, nom_affiche text, niveau_page text)
language sql
stable
security invoker
set search_path = ''
as $$ select * from private.classeur_personnes(); $$;
revoke execute on function public.classeur_personnes() from public, anon;
grant execute on function public.classeur_personnes() to authenticated;

commit;
