-- =============================================================================
-- OPTIONNEL — identité système « StayNTouch (PMS) » pour ÉTIQUETER l'auteur des
-- imports automatiques (daily_reports.imported_by).
--
-- ⚠ NE PAS exécuter l'ancien insert direct dans profiles : profiles.id est une FK
--   vers auth.users (compte réel). Un insert d'un id absent d'auth.users échoue
--   (erreur 23503 profiles_id_fkey). Le diagnostic ne voyait pas cette FK car elle
--   pointe vers le schéma protégé `auth`.
--
-- PAR DÉFAUT : on N'A PAS BESOIN de ce fichier. L'import auto écrit
-- daily_reports.imported_by = NULL (colonne nullable) → aucun compte à créer.
--
-- SI tu VEUX l'étiquette « importé par StayNTouch » :
--   1. Dashboard Supabase → Authentication → Users → Add user :
--        email : pms@stayntouch.system   (adresse fictive, aucun usage réel)
--        password : une longue chaîne aléatoire (jamais utilisée pour se connecter)
--      → cela crée proprement la ligne auth.users + (via trigger) la ligne profiles.
--   2. Récupère l'UUID du compte créé (colonne id dans la liste des users).
--   3. Renomme la fiche + verrouille le grade (exécute ci-dessous en remplaçant
--      <UUID> par l'UUID réel) :
--
--      update public.profiles
--        set display_name = 'StayNTouch (PMS)', role = 'utilisateur'
--        where id = '<UUID>';
--
--   4. Donne-moi cet UUID : je le mets dans supabase/functions/import-report/
--      repjour.ts (constante SYSTEM_IMPORTER_ID) à la place de null, et on
--      redéploie la fonction. Les imports auto s'afficheront alors « StayNTouch (PMS) ».
--
-- Le compte n'a AUCUN droit (role='utilisateur' + aucune permission de page) et
-- n'est pas destiné à la connexion : c'est une simple étiquette.
-- =============================================================================
