/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepjourRouteImport } from './routes/repjour'
import { Route as RaproRouteImport } from './routes/rapro'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PdjRouteImport } from './routes/pdj'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as AffichageRouteImport } from './routes/affichage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepjourIndexRouteImport } from './routes/repjour/index'
import { Route as RepjourAnalytiqueIndexRouteImport } from './routes/repjour/analytique.index'
import { Route as RepjourAnalytiqueYearMonthRouteImport } from './routes/repjour/analytique.$year.$month'

const RepjourRoute = RepjourRouteImport.update({
  id: '/repjour',
  path: '/repjour',
  getParentRoute: () => rootRouteImport,
} as any)
const RaproRoute = RaproRouteImport.update({
  id: '/rapro',
  path: '/rapro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PdjRoute = PdjRouteImport.update({
  id: '/pdj',
  path: '/pdj',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const AffichageRoute = AffichageRouteImport.update({
  id: '/affichage',
  path: '/affichage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepjourIndexRoute = RepjourIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepjourRoute,
} as any)
const RepjourAnalytiqueIndexRoute = RepjourAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => RepjourRoute,
} as any)
const RepjourAnalytiqueYearMonthRoute =
  RepjourAnalytiqueYearMonthRouteImport.update({
    id: '/analytique/$year/$month',
    path: '/analytique/$year/$month',
    getParentRoute: () => RepjourRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/caisse': typeof CaisseRoute
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/parking': typeof ParkingRoute
  '/pdj': typeof PdjRoute
  '/profil': typeof ProfilRoute
  '/rapro': typeof RaproRoute
  '/repjour': typeof RepjourRouteWithChildren
  '/repjour/': typeof RepjourIndexRoute
  '/repjour/analytique/': typeof RepjourAnalytiqueIndexRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/caisse': typeof CaisseRoute
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/parking': typeof ParkingRoute
  '/pdj': typeof PdjRoute
  '/profil': typeof ProfilRoute
  '/rapro': typeof RaproRoute
  '/repjour': typeof RepjourIndexRoute
  '/repjour/analytique': typeof RepjourAnalytiqueIndexRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/caisse': typeof CaisseRoute
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/parking': typeof ParkingRoute
  '/pdj': typeof PdjRoute
  '/profil': typeof ProfilRoute
  '/rapro': typeof RaproRoute
  '/repjour': typeof RepjourRouteWithChildren
  '/repjour/': typeof RepjourIndexRoute
  '/repjour/analytique/': typeof RepjourAnalytiqueIndexRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affichage'
    | '/caisse'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/parking'
    | '/pdj'
    | '/profil'
    | '/rapro'
    | '/repjour'
    | '/repjour/'
    | '/repjour/analytique/'
    | '/repjour/analytique/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affichage'
    | '/caisse'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/parking'
    | '/pdj'
    | '/profil'
    | '/rapro'
    | '/repjour'
    | '/repjour/analytique'
    | '/repjour/analytique/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/affichage'
    | '/caisse'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/parking'
    | '/pdj'
    | '/profil'
    | '/rapro'
    | '/repjour'
    | '/repjour/'
    | '/repjour/analytique/'
    | '/repjour/analytique/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffichageRoute: typeof AffichageRoute
  CaisseRoute: typeof CaisseRoute
  ComptesRoute: typeof ComptesRoute
  GestionRoute: typeof GestionRoute
  LoginRoute: typeof LoginRoute
  ParkingRoute: typeof ParkingRoute
  PdjRoute: typeof PdjRoute
  ProfilRoute: typeof ProfilRoute
  RaproRoute: typeof RaproRoute
  RepjourRoute: typeof RepjourRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repjour': {
      id: '/repjour'
      path: '/repjour'
      fullPath: '/repjour'
      preLoaderRoute: typeof RepjourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapro': {
      id: '/rapro'
      path: '/rapro'
      fullPath: '/rapro'
      preLoaderRoute: typeof RaproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdj': {
      id: '/pdj'
      path: '/pdj'
      fullPath: '/pdj'
      preLoaderRoute: typeof PdjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affichage': {
      id: '/affichage'
      path: '/affichage'
      fullPath: '/affichage'
      preLoaderRoute: typeof AffichageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repjour/': {
      id: '/repjour/'
      path: '/'
      fullPath: '/repjour/'
      preLoaderRoute: typeof RepjourIndexRouteImport
      parentRoute: typeof RepjourRoute
    }
    '/repjour/analytique/': {
      id: '/repjour/analytique/'
      path: '/analytique'
      fullPath: '/repjour/analytique/'
      preLoaderRoute: typeof RepjourAnalytiqueIndexRouteImport
      parentRoute: typeof RepjourRoute
    }
    '/repjour/analytique/$year/$month': {
      id: '/repjour/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/repjour/analytique/$year/$month'
      preLoaderRoute: typeof RepjourAnalytiqueYearMonthRouteImport
      parentRoute: typeof RepjourRoute
    }
  }
}

interface RepjourRouteChildren {
  RepjourIndexRoute: typeof RepjourIndexRoute
  RepjourAnalytiqueIndexRoute: typeof RepjourAnalytiqueIndexRoute
  RepjourAnalytiqueYearMonthRoute: typeof RepjourAnalytiqueYearMonthRoute
}

const RepjourRouteChildren: RepjourRouteChildren = {
  RepjourIndexRoute: RepjourIndexRoute,
  RepjourAnalytiqueIndexRoute: RepjourAnalytiqueIndexRoute,
  RepjourAnalytiqueYearMonthRoute: RepjourAnalytiqueYearMonthRoute,
}

const RepjourRouteWithChildren =
  RepjourRoute._addFileChildren(RepjourRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffichageRoute: AffichageRoute,
  CaisseRoute: CaisseRoute,
  ComptesRoute: ComptesRoute,
  GestionRoute: GestionRoute,
  LoginRoute: LoginRoute,
  ParkingRoute: ParkingRoute,
  PdjRoute: PdjRoute,
  ProfilRoute: ProfilRoute,
  RaproRoute: RaproRoute,
  RepjourRoute: RepjourRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
