/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepjourRouteImport } from './routes/repjour'
import { Route as RaproRouteImport } from './routes/rapro'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PdjRouteImport } from './routes/pdj'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as ArtefactRouteImport } from './routes/artefact'
import { Route as AffichageRouteImport } from './routes/affichage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepjourIndexRouteImport } from './routes/repjour/index'
import { Route as RaproIndexRouteImport } from './routes/rapro/index'
import { Route as PdjIndexRouteImport } from './routes/pdj/index'
import { Route as ParkingIndexRouteImport } from './routes/parking/index'
import { Route as CaisseIndexRouteImport } from './routes/caisse/index'
import { Route as RepjourAnalytiqueIndexRouteImport } from './routes/repjour/analytique.index'
import { Route as RaproAnalytiqueIndexRouteImport } from './routes/rapro/analytique.index'
import { Route as PdjAnalytiqueIndexRouteImport } from './routes/pdj/analytique.index'
import { Route as ParkingAnalytiqueIndexRouteImport } from './routes/parking/analytique.index'
import { Route as CaisseAnalytiqueIndexRouteImport } from './routes/caisse/analytique.index'
import { Route as RepjourAnalytiqueYearMonthRouteImport } from './routes/repjour/analytique.$year.$month'
import { Route as RaproAnalytiqueYearMonthRouteImport } from './routes/rapro/analytique.$year.$month'
import { Route as PdjAnalytiqueYearMonthRouteImport } from './routes/pdj/analytique.$year.$month'
import { Route as ParkingAnalytiqueYearMonthRouteImport } from './routes/parking/analytique.$year.$month'
import { Route as CaisseAnalytiqueYearMonthRouteImport } from './routes/caisse/analytique.$year.$month'

const RepjourRoute = RepjourRouteImport.update({
  id: '/repjour',
  path: '/repjour',
  getParentRoute: () => rootRouteImport,
} as any)
const RaproRoute = RaproRouteImport.update({
  id: '/rapro',
  path: '/rapro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PdjRoute = PdjRouteImport.update({
  id: '/pdj',
  path: '/pdj',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtefactRoute = ArtefactRouteImport.update({
  id: '/artefact',
  path: '/artefact',
  getParentRoute: () => rootRouteImport,
} as any)
const AffichageRoute = AffichageRouteImport.update({
  id: '/affichage',
  path: '/affichage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepjourIndexRoute = RepjourIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepjourRoute,
} as any)
const RaproIndexRoute = RaproIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RaproRoute,
} as any)
const PdjIndexRoute = PdjIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PdjRoute,
} as any)
const ParkingIndexRoute = ParkingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParkingRoute,
} as any)
const CaisseIndexRoute = CaisseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaisseRoute,
} as any)
const RepjourAnalytiqueIndexRoute = RepjourAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => RepjourRoute,
} as any)
const RaproAnalytiqueIndexRoute = RaproAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => RaproRoute,
} as any)
const PdjAnalytiqueIndexRoute = PdjAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => PdjRoute,
} as any)
const ParkingAnalytiqueIndexRoute = ParkingAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => ParkingRoute,
} as any)
const CaisseAnalytiqueIndexRoute = CaisseAnalytiqueIndexRouteImport.update({
  id: '/analytique/',
  path: '/analytique/',
  getParentRoute: () => CaisseRoute,
} as any)
const RepjourAnalytiqueYearMonthRoute =
  RepjourAnalytiqueYearMonthRouteImport.update({
    id: '/analytique/$year/$month',
    path: '/analytique/$year/$month',
    getParentRoute: () => RepjourRoute,
  } as any)
const RaproAnalytiqueYearMonthRoute =
  RaproAnalytiqueYearMonthRouteImport.update({
    id: '/analytique/$year/$month',
    path: '/analytique/$year/$month',
    getParentRoute: () => RaproRoute,
  } as any)
const PdjAnalytiqueYearMonthRoute = PdjAnalytiqueYearMonthRouteImport.update({
  id: '/analytique/$year/$month',
  path: '/analytique/$year/$month',
  getParentRoute: () => PdjRoute,
} as any)
const ParkingAnalytiqueYearMonthRoute =
  ParkingAnalytiqueYearMonthRouteImport.update({
    id: '/analytique/$year/$month',
    path: '/analytique/$year/$month',
    getParentRoute: () => ParkingRoute,
  } as any)
const CaisseAnalytiqueYearMonthRoute =
  CaisseAnalytiqueYearMonthRouteImport.update({
    id: '/analytique/$year/$month',
    path: '/analytique/$year/$month',
    getParentRoute: () => CaisseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/artefact': typeof ArtefactRoute
  '/caisse': typeof CaisseRouteWithChildren
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/parking': typeof ParkingRouteWithChildren
  '/pdj': typeof PdjRouteWithChildren
  '/profil': typeof ProfilRoute
  '/rapro': typeof RaproRouteWithChildren
  '/repjour': typeof RepjourRouteWithChildren
  '/caisse/': typeof CaisseIndexRoute
  '/parking/': typeof ParkingIndexRoute
  '/pdj/': typeof PdjIndexRoute
  '/rapro/': typeof RaproIndexRoute
  '/repjour/': typeof RepjourIndexRoute
  '/caisse/analytique/': typeof CaisseAnalytiqueIndexRoute
  '/parking/analytique/': typeof ParkingAnalytiqueIndexRoute
  '/pdj/analytique/': typeof PdjAnalytiqueIndexRoute
  '/rapro/analytique/': typeof RaproAnalytiqueIndexRoute
  '/repjour/analytique/': typeof RepjourAnalytiqueIndexRoute
  '/caisse/analytique/$year/$month': typeof CaisseAnalytiqueYearMonthRoute
  '/parking/analytique/$year/$month': typeof ParkingAnalytiqueYearMonthRoute
  '/pdj/analytique/$year/$month': typeof PdjAnalytiqueYearMonthRoute
  '/rapro/analytique/$year/$month': typeof RaproAnalytiqueYearMonthRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/artefact': typeof ArtefactRoute
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/caisse': typeof CaisseIndexRoute
  '/parking': typeof ParkingIndexRoute
  '/pdj': typeof PdjIndexRoute
  '/rapro': typeof RaproIndexRoute
  '/repjour': typeof RepjourIndexRoute
  '/caisse/analytique': typeof CaisseAnalytiqueIndexRoute
  '/parking/analytique': typeof ParkingAnalytiqueIndexRoute
  '/pdj/analytique': typeof PdjAnalytiqueIndexRoute
  '/rapro/analytique': typeof RaproAnalytiqueIndexRoute
  '/repjour/analytique': typeof RepjourAnalytiqueIndexRoute
  '/caisse/analytique/$year/$month': typeof CaisseAnalytiqueYearMonthRoute
  '/parking/analytique/$year/$month': typeof ParkingAnalytiqueYearMonthRoute
  '/pdj/analytique/$year/$month': typeof PdjAnalytiqueYearMonthRoute
  '/rapro/analytique/$year/$month': typeof RaproAnalytiqueYearMonthRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affichage': typeof AffichageRoute
  '/artefact': typeof ArtefactRoute
  '/caisse': typeof CaisseRouteWithChildren
  '/comptes': typeof ComptesRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/parking': typeof ParkingRouteWithChildren
  '/pdj': typeof PdjRouteWithChildren
  '/profil': typeof ProfilRoute
  '/rapro': typeof RaproRouteWithChildren
  '/repjour': typeof RepjourRouteWithChildren
  '/caisse/': typeof CaisseIndexRoute
  '/parking/': typeof ParkingIndexRoute
  '/pdj/': typeof PdjIndexRoute
  '/rapro/': typeof RaproIndexRoute
  '/repjour/': typeof RepjourIndexRoute
  '/caisse/analytique/': typeof CaisseAnalytiqueIndexRoute
  '/parking/analytique/': typeof ParkingAnalytiqueIndexRoute
  '/pdj/analytique/': typeof PdjAnalytiqueIndexRoute
  '/rapro/analytique/': typeof RaproAnalytiqueIndexRoute
  '/repjour/analytique/': typeof RepjourAnalytiqueIndexRoute
  '/caisse/analytique/$year/$month': typeof CaisseAnalytiqueYearMonthRoute
  '/parking/analytique/$year/$month': typeof ParkingAnalytiqueYearMonthRoute
  '/pdj/analytique/$year/$month': typeof PdjAnalytiqueYearMonthRoute
  '/rapro/analytique/$year/$month': typeof RaproAnalytiqueYearMonthRoute
  '/repjour/analytique/$year/$month': typeof RepjourAnalytiqueYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affichage'
    | '/artefact'
    | '/caisse'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/parking'
    | '/pdj'
    | '/profil'
    | '/rapro'
    | '/repjour'
    | '/caisse/'
    | '/parking/'
    | '/pdj/'
    | '/rapro/'
    | '/repjour/'
    | '/caisse/analytique/'
    | '/parking/analytique/'
    | '/pdj/analytique/'
    | '/rapro/analytique/'
    | '/repjour/analytique/'
    | '/caisse/analytique/$year/$month'
    | '/parking/analytique/$year/$month'
    | '/pdj/analytique/$year/$month'
    | '/rapro/analytique/$year/$month'
    | '/repjour/analytique/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affichage'
    | '/artefact'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/profil'
    | '/caisse'
    | '/parking'
    | '/pdj'
    | '/rapro'
    | '/repjour'
    | '/caisse/analytique'
    | '/parking/analytique'
    | '/pdj/analytique'
    | '/rapro/analytique'
    | '/repjour/analytique'
    | '/caisse/analytique/$year/$month'
    | '/parking/analytique/$year/$month'
    | '/pdj/analytique/$year/$month'
    | '/rapro/analytique/$year/$month'
    | '/repjour/analytique/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/affichage'
    | '/artefact'
    | '/caisse'
    | '/comptes'
    | '/gestion'
    | '/login'
    | '/parking'
    | '/pdj'
    | '/profil'
    | '/rapro'
    | '/repjour'
    | '/caisse/'
    | '/parking/'
    | '/pdj/'
    | '/rapro/'
    | '/repjour/'
    | '/caisse/analytique/'
    | '/parking/analytique/'
    | '/pdj/analytique/'
    | '/rapro/analytique/'
    | '/repjour/analytique/'
    | '/caisse/analytique/$year/$month'
    | '/parking/analytique/$year/$month'
    | '/pdj/analytique/$year/$month'
    | '/rapro/analytique/$year/$month'
    | '/repjour/analytique/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffichageRoute: typeof AffichageRoute
  ArtefactRoute: typeof ArtefactRoute
  CaisseRoute: typeof CaisseRouteWithChildren
  ComptesRoute: typeof ComptesRoute
  GestionRoute: typeof GestionRoute
  LoginRoute: typeof LoginRoute
  ParkingRoute: typeof ParkingRouteWithChildren
  PdjRoute: typeof PdjRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  RaproRoute: typeof RaproRouteWithChildren
  RepjourRoute: typeof RepjourRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repjour': {
      id: '/repjour'
      path: '/repjour'
      fullPath: '/repjour'
      preLoaderRoute: typeof RepjourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapro': {
      id: '/rapro'
      path: '/rapro'
      fullPath: '/rapro'
      preLoaderRoute: typeof RaproRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdj': {
      id: '/pdj'
      path: '/pdj'
      fullPath: '/pdj'
      preLoaderRoute: typeof PdjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artefact': {
      id: '/artefact'
      path: '/artefact'
      fullPath: '/artefact'
      preLoaderRoute: typeof ArtefactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affichage': {
      id: '/affichage'
      path: '/affichage'
      fullPath: '/affichage'
      preLoaderRoute: typeof AffichageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repjour/': {
      id: '/repjour/'
      path: '/'
      fullPath: '/repjour/'
      preLoaderRoute: typeof RepjourIndexRouteImport
      parentRoute: typeof RepjourRoute
    }
    '/rapro/': {
      id: '/rapro/'
      path: '/'
      fullPath: '/rapro/'
      preLoaderRoute: typeof RaproIndexRouteImport
      parentRoute: typeof RaproRoute
    }
    '/pdj/': {
      id: '/pdj/'
      path: '/'
      fullPath: '/pdj/'
      preLoaderRoute: typeof PdjIndexRouteImport
      parentRoute: typeof PdjRoute
    }
    '/parking/': {
      id: '/parking/'
      path: '/'
      fullPath: '/parking/'
      preLoaderRoute: typeof ParkingIndexRouteImport
      parentRoute: typeof ParkingRoute
    }
    '/caisse/': {
      id: '/caisse/'
      path: '/'
      fullPath: '/caisse/'
      preLoaderRoute: typeof CaisseIndexRouteImport
      parentRoute: typeof CaisseRoute
    }
    '/repjour/analytique/': {
      id: '/repjour/analytique/'
      path: '/analytique'
      fullPath: '/repjour/analytique/'
      preLoaderRoute: typeof RepjourAnalytiqueIndexRouteImport
      parentRoute: typeof RepjourRoute
    }
    '/rapro/analytique/': {
      id: '/rapro/analytique/'
      path: '/analytique'
      fullPath: '/rapro/analytique/'
      preLoaderRoute: typeof RaproAnalytiqueIndexRouteImport
      parentRoute: typeof RaproRoute
    }
    '/pdj/analytique/': {
      id: '/pdj/analytique/'
      path: '/analytique'
      fullPath: '/pdj/analytique/'
      preLoaderRoute: typeof PdjAnalytiqueIndexRouteImport
      parentRoute: typeof PdjRoute
    }
    '/parking/analytique/': {
      id: '/parking/analytique/'
      path: '/analytique'
      fullPath: '/parking/analytique/'
      preLoaderRoute: typeof ParkingAnalytiqueIndexRouteImport
      parentRoute: typeof ParkingRoute
    }
    '/caisse/analytique/': {
      id: '/caisse/analytique/'
      path: '/analytique'
      fullPath: '/caisse/analytique/'
      preLoaderRoute: typeof CaisseAnalytiqueIndexRouteImport
      parentRoute: typeof CaisseRoute
    }
    '/repjour/analytique/$year/$month': {
      id: '/repjour/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/repjour/analytique/$year/$month'
      preLoaderRoute: typeof RepjourAnalytiqueYearMonthRouteImport
      parentRoute: typeof RepjourRoute
    }
    '/rapro/analytique/$year/$month': {
      id: '/rapro/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/rapro/analytique/$year/$month'
      preLoaderRoute: typeof RaproAnalytiqueYearMonthRouteImport
      parentRoute: typeof RaproRoute
    }
    '/pdj/analytique/$year/$month': {
      id: '/pdj/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/pdj/analytique/$year/$month'
      preLoaderRoute: typeof PdjAnalytiqueYearMonthRouteImport
      parentRoute: typeof PdjRoute
    }
    '/parking/analytique/$year/$month': {
      id: '/parking/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/parking/analytique/$year/$month'
      preLoaderRoute: typeof ParkingAnalytiqueYearMonthRouteImport
      parentRoute: typeof ParkingRoute
    }
    '/caisse/analytique/$year/$month': {
      id: '/caisse/analytique/$year/$month'
      path: '/analytique/$year/$month'
      fullPath: '/caisse/analytique/$year/$month'
      preLoaderRoute: typeof CaisseAnalytiqueYearMonthRouteImport
      parentRoute: typeof CaisseRoute
    }
  }
}

interface CaisseRouteChildren {
  CaisseIndexRoute: typeof CaisseIndexRoute
  CaisseAnalytiqueIndexRoute: typeof CaisseAnalytiqueIndexRoute
  CaisseAnalytiqueYearMonthRoute: typeof CaisseAnalytiqueYearMonthRoute
}

const CaisseRouteChildren: CaisseRouteChildren = {
  CaisseIndexRoute: CaisseIndexRoute,
  CaisseAnalytiqueIndexRoute: CaisseAnalytiqueIndexRoute,
  CaisseAnalytiqueYearMonthRoute: CaisseAnalytiqueYearMonthRoute,
}

const CaisseRouteWithChildren =
  CaisseRoute._addFileChildren(CaisseRouteChildren)

interface ParkingRouteChildren {
  ParkingIndexRoute: typeof ParkingIndexRoute
  ParkingAnalytiqueIndexRoute: typeof ParkingAnalytiqueIndexRoute
  ParkingAnalytiqueYearMonthRoute: typeof ParkingAnalytiqueYearMonthRoute
}

const ParkingRouteChildren: ParkingRouteChildren = {
  ParkingIndexRoute: ParkingIndexRoute,
  ParkingAnalytiqueIndexRoute: ParkingAnalytiqueIndexRoute,
  ParkingAnalytiqueYearMonthRoute: ParkingAnalytiqueYearMonthRoute,
}

const ParkingRouteWithChildren =
  ParkingRoute._addFileChildren(ParkingRouteChildren)

interface PdjRouteChildren {
  PdjIndexRoute: typeof PdjIndexRoute
  PdjAnalytiqueIndexRoute: typeof PdjAnalytiqueIndexRoute
  PdjAnalytiqueYearMonthRoute: typeof PdjAnalytiqueYearMonthRoute
}

const PdjRouteChildren: PdjRouteChildren = {
  PdjIndexRoute: PdjIndexRoute,
  PdjAnalytiqueIndexRoute: PdjAnalytiqueIndexRoute,
  PdjAnalytiqueYearMonthRoute: PdjAnalytiqueYearMonthRoute,
}

const PdjRouteWithChildren = PdjRoute._addFileChildren(PdjRouteChildren)

interface RaproRouteChildren {
  RaproIndexRoute: typeof RaproIndexRoute
  RaproAnalytiqueIndexRoute: typeof RaproAnalytiqueIndexRoute
  RaproAnalytiqueYearMonthRoute: typeof RaproAnalytiqueYearMonthRoute
}

const RaproRouteChildren: RaproRouteChildren = {
  RaproIndexRoute: RaproIndexRoute,
  RaproAnalytiqueIndexRoute: RaproAnalytiqueIndexRoute,
  RaproAnalytiqueYearMonthRoute: RaproAnalytiqueYearMonthRoute,
}

const RaproRouteWithChildren = RaproRoute._addFileChildren(RaproRouteChildren)

interface RepjourRouteChildren {
  RepjourIndexRoute: typeof RepjourIndexRoute
  RepjourAnalytiqueIndexRoute: typeof RepjourAnalytiqueIndexRoute
  RepjourAnalytiqueYearMonthRoute: typeof RepjourAnalytiqueYearMonthRoute
}

const RepjourRouteChildren: RepjourRouteChildren = {
  RepjourIndexRoute: RepjourIndexRoute,
  RepjourAnalytiqueIndexRoute: RepjourAnalytiqueIndexRoute,
  RepjourAnalytiqueYearMonthRoute: RepjourAnalytiqueYearMonthRoute,
}

const RepjourRouteWithChildren =
  RepjourRoute._addFileChildren(RepjourRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffichageRoute: AffichageRoute,
  ArtefactRoute: ArtefactRoute,
  CaisseRoute: CaisseRouteWithChildren,
  ComptesRoute: ComptesRoute,
  GestionRoute: GestionRoute,
  LoginRoute: LoginRoute,
  ParkingRoute: ParkingRouteWithChildren,
  PdjRoute: PdjRouteWithChildren,
  ProfilRoute: ProfilRoute,
  RaproRoute: RaproRouteWithChildren,
  RepjourRoute: RepjourRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
